### ISSUE TITLE
[dired-narrow]-change cursor shape/color in filter mode?

### ISSUE THREAD

**Issue by zeltak** [Fuco1/dired-hacks#65]
Hi again

been using dired-narrow (and all of dired hacks) for months now and love it (TBH its what allowed me to move to dired as my full time FM :))

so one thing that makes life "tough" for me is that when in filter mode the cursor switches from my normal dired cursor (a blue line-- using hl-line-mode 1) to an empty blue box. here is a screenshot:

https://paste.xinu.at/5oR/

is there anyway to make filter mode keep the hl-line-mode to be 1)consistent with dired and 2)get better visual feedback on where the cursor is?

thx alot

Z

**Comment by Fuco1** [comment]
This happens because the current window changes to the minibuffer (where you get the filled box = active window).

I suppose emacs allows to change the visuals somehow.  Isearch also solves this but they use different hack.

**Comment by Fuco1** [comment]
So, we can do it using this variable

```
cursor-in-non-selected-windows is a variable defined in `C source code'.
Its value is t

  Automatically becomes buffer-local when set.

Documentation:
Non-nil means show a cursor in non-selected windows.
If nil, only shows a cursor in the selected window.
If t, displays a cursor related to the usual cursor type
(a solid box becomes hollow, a bar becomes a narrower bar).
You can also specify the cursor type as in the `cursor-type' variable.
Use Custom to set this variable and update the display.
```

Basically, the solution is to temporarily change the value of this variable to `cursor-type`, and on exiting narrow mode restoring it back to whatever it was before.

If you are interested in providing a patch, please let me know, otherwise I'll put it to my task queue somewhere.

**Comment by zeltak** [comment]
thx so much for the info

unfortunately i cant code to save my life (im an academic in the humanities and thus suck st coding :))
would be great if this could be added at some point as i believe it will increase usability :)

best and thx again

Z

**Comment by sandric** [comment]
Hm didn't worked for me.. I tried to set like this, is this wrong: 
`(setq cursor-in-non-selected-windows cursor-type)`

**Comment by sandric** [comment]
Ok it looks like I fixed it, the thing was to place `(hl-line-highlight)` at the end of `dired-narrow--live-update` function. Here's full function with added three last lines:

```elisp
          (defun dired-narrow--live-update ()
            "Update the dired buffer based on the contents of the minibuffer."
            (when dired-narrow-buffer
              (let ((current-filter (minibuffer-contents-no-properties)))
                (with-current-buffer dired-narrow-buffer
                  (unless (equal current-filter dired-narrow--minibuffer-content)
                    (dired-narrow--update current-filter))
                  (setq dired-narrow--minibuffer-content current-filter)
                  (setq dired-narrow--current-file (dired-utils-get-filename))
                  (set-window-point (get-buffer-window (current-buffer)) (point))

                  (when (bound-and-true-p hl-line-mode)
                    (hl-line-highlight))))))
```

Is this fixes the original issue, should I make PR with this?

**Comment by Fuco1** [comment]
I have no idea what `hl-line-mode` is but I don't think it should be relevant here.  Where did you put the `setq`?

Feel free to open a pull request if it's not too much hussle, it's much easier to review code that way :)

**Comment by sandric** [comment]
Well its what this issue is about and what @zeltak asked 

> so one thing that makes life "tough" for me is that when in filter mode the cursor switches from my normal dired cursor (a blue line-- using hl-line-mode 1) to an empty blue box.

I may misunderstood the issue if thats the same as I have problems with. My problem is that when you enable `hl-line-mode` (default mode in emacs to highlight current line) in dired - after enabling `dired-narrow` and starting to search or move in found filenames - only cursor moves and line on which cursor is - not get highlighted.
So the `hl-line-highlight` is simple function that takes cursor position and highlights the whole line with color.

And if you ask me why wasn't it highlighted without placing that function than I have no clue).

I tried to place `(setq cursor-in-non-selected-windows cursor-type)` in several places - to simply evaluate globally, to run with dired hook or with narrow active - no results as for me.

**Comment by Fuco1** [comment]
Right, now I understand the issue better.  In this case it probably makes sense to call `hl-line-highlight` indeed.

That still doesn't change the cursor shape though, does it?  Maybe you could stick the `setq` form right after the `when` condition you've added, I think that should work (but you need to memorize `cursor-type` before entering `with-current-buffer` because otherwise you'd just set it to the same value)

**Comment by sandric** [comment]
Ahh now I don't really know the issue - never changed cursor shape) Ok I'll try then to change and memorize it and write here final function if it will work to be sure that pr is adequate.
